### ISSUE TITLE
Please deprecate the old package

### ISSUE THREAD

**Issue by dandv** [vicanso/influxdb-nodejs#10]
https://github.com/npms-io/npms-www/issues/112#issuecomment-252550752

Thanks!

**Comment by vicanso** [comment]
@dandv 
Done!

**Comment by satazor** [comment]
@vicanso how did you deprecated the module? Looking at https://skimdb.npmjs.com/registry/influxdb-nodejs it seems to not be deprecated.

**Comment by vicanso** [comment]
@satazor influxdb-nodejs is maintained and the simple-influx is  deprecated.

**Comment by satazor** [comment]
Oh sorry, looked at the wrong package!
