### ISSUE TITLE
How can I get only specific fields from influx.

### ISSUE THREAD

**Issue by sunilkumarnaik** [vicanso/influxdb-nodejs#12]
Hi,
  How can I get only specific fields data from influx. 
 For Ex. SELECT FIELD1, FIELD2, FIELD2  FROM  TABLE

**Comment by vicanso** [comment]
@sunilkumarnaik 
```js
client.query('table')
  .addField('field1', 'field2', 'field3');
```

**Comment by sunilkumarnaik** [comment]
Hi,
  How can we put **or** condition, like the following query.

  SELECT FIELD1, FIELD2, FIELD2 FROM TABLE WHERE FIELD4="condn1" or FIELD4="condn2"

**Comment by vicanso** [comment]
@sunilkumarnaik  

The default of condition function is  `and`, eg:
```js
// select "field1","field2" from "table" where "field1" = 'con1' and "field2" = 'con2'
client.query('table')
  .addField('field1', 'field2')
  .condition('field1', 'con1')
  .condition('field2', 'con2')
  .then(console.info);
```

If you want to use `or`, eg:
```js
// select * from "table" where field1 = 'con1' or field2 = 'con1'
client.query('table')
  .condition("field1 = 'con1' or field2 = 'con1'")
 .then(console.info);
```

I will write a better API asap.

**Comment by vicanso** [comment]
@sunilkumarnaik 

[API](http://vicanso.github.io/influxdb-nodejs/Client.html) was written.

**Comment by sunilkumarnaik** [comment]
Thanks  @vicanso
