### ISSUE TITLE
Values that end in i are not being converted to string.

### ISSUE THREAD

**Issue by Snipa22** [vicanso/influxdb-nodejs#14]
Per: https://github.com/vicanso/influxdb-nodejs/blob/master/lib/influx.js#L28

It appears that strings that end in an i, are not being converted to strings.  I'm not entirely sure why this is like this, except perhaps for debugging, as it causes errors as follows:
influxdb-nodejs writer data:{"measurement":"shares","tags":{"foundBlock":false,"shareType":"valid","paymentType":"pplns","poolID":2,"blockDiff":6664436299,"bitcoin":0,"worker_tag":"mini","payout_tag":"<Munged>"},"fields":{"round":1219169,"shares":1000,"worker":"mini","payout":"<Munged>"},"time":1483862223761,"precision":"ms"} +16s
influxdb-nodejs POST /write, data:"shares,foundBlock=false,shareType=valid,paymentType=pplns,poolID=2,blockDiff=6664436299,bitcoin=0,worker_tag=mini,payout_tag=<Munged>round=1219169,shares=1000,worker=mini,payout=\"<Munged>\" 1483862223761", query:{"db":"<Munged>","u":"<Munged>","p":"<Munged>","precision":"ms"} +1ms

As you can see, the worker field, is not being properly escaped, which is causing it to throw invalid boolean errors.

I'm not sure if this is a debug thing (I assume it is?), but I don't want to submit a patch without knowing what it's there for.

**Comment by Snipa22** [comment]
I stand corrected, this is so influxdb shunts the string value to an integer, however, it appears that influxdb handles the integer type correctly, so is this fully needed?  As this interrupts fully the insert of strings, I'm not sure how useful this is.

**Comment by vicanso** [comment]
this is a bug. I will fix it asap

2017年1月8日 下午4:20，"Snipa22" <notifications@github.com>写道：

**Comment by vicanso** [comment]
@Snipa22  The new version 2.4.2 is published.
