### ISSUE TITLE
question about timestamp

### ISSUE THREAD

**Issue by joyhope** [vicanso/influxdb-nodejs#16]
I use queue to do batch insert points. The timestamp seems be updated by the queue itself. 

`queue() {
    const internalData = internal(this);
    const queue = internalData.queue;
    /* istanbul ignore if */
    if (!queue) {
      throw new Error('queue function is undefined');
    }
    this.time(util.getTime(internalData.precision));
    queue(this.toJSON());
    return this;
  }
}
`

util.getTime(internalData.precision)  seems reset the previous timestamp.  I think it is not proper.  Current logical caused lost the preset timestamps.

**Comment by vicanso** [comment]
@joyhope
