### ISSUE TITLE
Write error with tags

### ISSUE THREAD

**Issue by florentb** [vicanso/influxdb-nodejs#17]
Seems to be an issue with writing tags.

> InfluxDB version 1.2.2

```js
'use strict';

const influx = require('influxdb-nodejs');

const influxCli = new influx('http://localhost:8086/test');

influxCli.writePoint('test_measurement',
  { testBoolean: true, testString: 'test', testInteger: 1, testFloat: 0.1 },
  { testTag: 'test', testAnothertag: 'test' }
).then(() => console.info('write point success')).catch(err => console.error(err));
```

This result with an error: `[TypeError: this is not a typed array.]`

The same request is OK when no tags are provided.

**Comment by vicanso** [comment]
I run successful and found data in inflxudb:

```
name: test_measurement
time                testAnothertag testBoolean testFloat testInteger testString testTag
----                -------------- ----------- --------- ----------- ---------- -------
1490703839291838301 test           true        0.1       1           test       test
```

Then I found that in then version 4.0.0, `Buffer.from` function will throw an error like the problem you mentioned. I suggest you use the latest version of node.js or the latest version of 4.x

I will fix it asap.
