### ISSUE TITLE
epoch not passed to Influx.query

### ISSUE THREAD

**Issue by sebastienfouss** [vicanso/influxdb-nodejs#18]
It seems that the "epoch" value is not passed to the Influx.query.

More precisely, in influx.js, function query accepts 3 parameters: query(q, db, epoch).
However, when called by function syncQuery in client.js, only the first parameter is passed, therefore the epoch is undefined and ignore when influxDB is queried.

One way to solve this is to modify the following line in client.js, line 752:
return influx.query(arr.join(';')).then((data) => {

shall become
return influx.query(arr.join(';'), null, internal(this).options.epoch).then((data) => {

However, I'm not sure that this is the right approach.

**Comment by vicanso** [comment]
@sebastienfouss  I think your approach is workable.  You can pull a request to fix it and remember to add test case.
