### ISSUE TITLE
Server connection failure

### ISSUE THREAD

**Issue by anthonywebb** [vicanso/influxdb-nodejs#20]
Curious if there is a method to detect if the connection to influxdb was successful or failed?

**Comment by vicanso** [comment]
@anthonywebb  You can use `curl http://127.0.0.1:8086/ping`, if influxdb is healthy, it will return `204 No Content`.

If you use `influxdb-relay`  for high availability, you should use `influxdb-nodejs` like this:

```js
const client = new Influx('http://127.0.0.1:9086,127.0.0.1:9097/mydb', {
  loadBalancingAlgorithm: 'round-robin',
});
client.startHealthCheck();
```

You can get more demo from [API](https://vicanso.github.io/influxdb-nodejs/index.html)
