### ISSUE TITLE
[Question] findOneAndUpdate example

### ISSUE THREAD

**Issue by SilvaLA59** [vicanso/influxdb-nodejs#24]
Hello,
Is there any example how to use client.findOneAndUpdate() ?

**Comment by vicanso** [comment]
@SilvaLA59 The tags and time confirm the influxdb's point, if you wanna update this point, you should get the tags and time first.

```js
client.write('measurement')
  .tag(updatePointTags)
  .time(updatePointTime)
  // these fields will be updated
  .field({
    use: 300,
    code: 200,
  })
```
