### ISSUE TITLE
Add comma separated multi statement

### ISSUE THREAD

**Issue by Trucc** [vicanso/influxdb-nodejs#27]
Refering to [Influxdb Multi statement]( https://docs.influxdata.com/influxdb/v1.5/query_language/data_exploration/#multiple-statements)

It would be awesome to have a QL that would handle mutli statement over the HTTP API without doing like this :

` 
var QL = [];
QL.push(client.query("temperature").addField("value").where("device", query.device).where('time',query.to.unix()*1000000000, "<").toSelect())
QL.push(client.query("temperature").addField("value").where("device", query.device).where('time', query.to.unix()*1000000000, "<").toSelect())
var datas = await client.queryPost(QL.join(";"),"test")`

**Comment by vicanso** [comment]
@Trucc  Thanks, I will support it in the next version

**Comment by vicanso** [comment]
@Trucc You can try it in the version 2.8.0

**Comment by Trucc** [comment]
Seems good, thanks !
