### ISSUE TITLE
How to initialize a self certificate ssl connection？

### ISSUE THREAD

**Issue by ash0080** [vicanso/influxdb-nodejs#28]
![2018-09-07 5 45 38](https://user-images.githubusercontent.com/2803210/45211832-ebd97a80-b2c5-11e8-9b49-d4242dae3995.png)
like this option does in chronograf

Sorry for stupid question, noticed that it uses a HTTP module, so doesn't support https connection now.

**Comment by vicanso** [comment]
@ash0080 `Influxdb-nodejs` is using `superagent` to handle http(https) requests. If you want to use `self certificate ssl`, you just need to set nodejs env `NODE_TLS_REJECT_UNAUTHORIZED=0`.

**Comment by ash0080** [comment]
Get it, Thank you
