### ISSUE TITLE
Basic Auth

### ISSUE THREAD

**Issue by Cerbis** [vicanso/influxdb-nodejs#29]
I'm looking for a way to use basic authentication. Have i overlooked a detail or isn't it currently possible?

**Comment by vicanso** [comment]
You can use like this:

```js
const client = new Client("http://vicanso:mypwd@localhost:8086/db");
```

**Comment by Cerbis** [comment]
That way the username and password is set as query-parameter which looks like this:
`"POST /write?db=database_name&u=user&p=password HTTP/1.1"`
Basic auth sets the username and password as header. My problem is that a proxy between the application and influxdb would log the username and password.

**Comment by vicanso** [comment]
I misunderstood the basic authentication. I will support it in the next version.

**Comment by vicanso** [comment]
In the verion 2.9.0, you can use like this:

```js
const Influx = require('influxdb-nodejs');
const client = new Influx('http://user:pwd@127.0.0.1:8086/mydb?auth=basic');
```
