### ISSUE TITLE
Adding RP for existing DB

### ISSUE THREAD

**Issue by hwa123** [vicanso/influxdb-nodejs#31]
Is it possible to add option to pass the name of database to createRetentionPolicy()? Similar functionality like this
`
InfluxQL.createRP(name, database, duration, shardDuration, replication, isDefault);
`
https://github.com/vicanso/influxdb-nodejs/blob/master/lib/client.js#L396

**Comment by vicanso** [comment]
When you new a Client instance, the name of database is appointed. And the `Client. createRetentionPolicy` function is for the database that you initiated.

```js
const client = new Influx('http://127.0.0.1:8086/mydb');
// create retention policy for mydb
client.createRetentionPolicy(name, duration, replication, shardDuration, isDefault);
```

**Comment by hwa123** [comment]
@vicanso Thanks, got it.
