### ISSUE TITLE
时区问题:请问influxdb-nodejs是否可以加入设置时区功能

### ISSUE THREAD

**Issue by soonco** [vicanso/influxdb-nodejs#32]
select count(*) from expose where time > 1545667200000ms and time<1545753599999ms  group by time(1d)
得到2天数据

select count(*) from expose where time > 1545667200000ms and time<1545753599999ms  group by time(1d) tz('Asia/Shanghai')
得到1天数据

**Comment by vicanso** [comment]
In version 2.10.0, support to set timezone like this:
```js
client.query('http')
  .set({
    tz: 'America/Chicago',
  })
```

**Comment by soonco** [comment]
@vicanso 收到，非常感谢
