### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by alexeymarunin** [vicanso/influxdb-nodejs#33]
Hello @vicanso !

Can you add proxy support for influxdb-nodejs reader/writer? 
May be [superagent-proxy](https://github.com/TooTallNate/superagent-proxy) plugin will be useful

**Comment by vicanso** [comment]
@alexeymarunin  You can use [addPlugin](https://vicanso.github.io/influxdb-nodejs/Client.html#addPlugin) function. It's the same as superagent use function.

```js
const noCache = require('superagent-no-cache')
client.addPlugin(noCache);
```

By the way, the `addPlugin` function is supported since 2.11.0.

**Comment by alexeymarunin** [comment]
@vicanso thanks, I'll try it)
