### ISSUE TITLE
Connect to InfluxDB cluster 

### ISSUE THREAD

**Issue by kedardahivale** [vicanso/influxdb-nodejs#36]
Hello, 
I am relatively new to this Lib, I was hoping has anyone tried connecting a client to a cluster? 
or is it possible to connect to InfluxDB cluster?

**Comment by vicanso** [comment]
Could you show me the influxdb cluster solution, which isn't open source.

**Comment by kedardahivale** [comment]
@vicanso  I couldn't exactly get you?  correct me If I am wrong, do you mean there is no open source library/npm library which will connect the influx client to influxDB cluster? is it possible to use the influxdb-nodejs library to connect to influxDB cluster? If I understood it you wrong then really sorry

**Comment by vicanso** [comment]
@kedardahivale 

I mean that I haven't used influxdb cluster so I am not sure about the outcome of it. Can you tell me the solution of cluster that you use, [influxdb-relay](https://github.com/influxdata/influxdb-relay) or InfluxDB Cloud?

If you use `influxdb-relay`,  the connection uri shoul be [http://user:pass@localhost:port,anotherhost:port,yetanother:port/mydatabase](https://github.com/vicanso/influxdb-nodejs/blob/master/lib/client.js#L64).

**Comment by kedardahivale** [comment]
@vicanso  sorry for the delay!
Currently I am running the influxdb cluster [](https://github.com/amancevice/docker-influxdb-cluster) and I don't think it is influxdb-relay.

**Comment by vicanso** [comment]
You may try this solution [http://user:pass@localhost:port,anotherhost:port,yetanother:port/mydatabase](https://github.com/vicanso/influxdb-nodejs/blob/master/lib/client.js#L64).

**Comment by kedardahivale** [comment]
@vicanso  Hey! we can close the issue.
Thanks for your help
