### ISSUE TITLE
Add precision for timestamp during write

### ISSUE THREAD

**Issue by cEhlen** [vicanso/influxdb-nodejs#4]
I need a way to set the precision of the given timestamp set with .time(x).
Like documented in the [influxdb docs](https://docs.influxdata.com/influxdb/v0.13/write_protocols/write_syntax/#query-string-parameters-for-writes).

`
client.write('sensor').time(1463412366717).precision('ms');
`

I will send a pull request soon.

**Comment by sveip** [comment]
Hi, I tried the precision feature, but got an error when I write to Influx. I get an `time outside range 1677-09-21 00:12:43.145224192 +0000 UTC - 2262-04-11 23:47:16.854775807 +0000 UTC` error which is not there when I don't specify the precision argument.

Another thing, I added the field to the `writePoint` method, and it seems to work (besides the error above)
```javascript
/**
   * [writePoint description]
   * @param  {[type]} measurement [description]
   * @param  {[type]} fields      [description]
   * @param  {[type]} tags        [description]
   * @return {[type]}             [description]
   */
  writePoint(measurement, fields, tags, precision) {
    const writer = this.write(measurement);
    writer.field(fields);
    if (tags) {
      writer.tag(tags);
    }
    writer.precision = precision;
    return writer;
  }
```

I'm a novice js coder, so it might be wrong though. Let me know what you think.

**Comment by cEhlen** [comment]
Strange. The test suit finishes without errors on my machine.
[write point with time](https://github.com/vicanso/influxdb-nodejs/blob/d630d9ebb4e0ac555c3b2d0ae814b81795259910/test/writer.js#L59) should test for such an error.

Could you show the exact call you are using?

**Comment by sveip** [comment]
Hi, this is it:

```javascript
const writePoint = (client, statData) => {
  statData.stats.map(function(stat){
    const tag = {
      first: firstVal,
      second: secondVal
    };
    const fields = {
      first: stat.firstField,
      second: stat.secondField
    };
    client.writePoint('myDB', fields, tag)
      .then(data => {
        console.log("Write to Influx successful", data);
      })
      .catch(err => {
        console.log("err", err);
      });
  });
};
```

**Comment by cEhlen** [comment]
I got the error if I set the precision to something else than 'n' but don't manually set the time.

The default behavior is to set the time to nanoseconds. I will change this, so we build the default timestamp based on the current precision.

Is this the same error you've got?

My test code:
```js
'use strict';
const Influx = require('./index');
const client = new Influx('http://root:root@127.0.0.1:8086/myDB');

const tag = {
  foo: 'test',
  bar: 'foo',
};

const fields = {
  first: 1,
  second: 2,
};

client.writePoint('myDB', fields, tag)
  .then(data => {
    console.log("Write to Influx successful", data);
  })
  .catch(err => {
    console.log("err", err);
  });
```

**Comment by sveip** [comment]
Correct, I don't specify time explicitly. 

Will you also add the precision field to the writePoint method while you are at it?

**Comment by cEhlen** [comment]
Sounds good. I will make a pull request soon.

**Comment by cEhlen** [comment]
Why are we setting the current timestamp if the time is not explicitly set? [InfluxDB will set the current time as timestamp if it was not transmitted](https://docs.influxdata.com/influxdb/v0.13/write_protocols/write_syntax/#timestamps). This seems like a sane default.

By just removing [the check if a time is set](https://github.com/vicanso/influxdb-nodejs/blob/d630d9ebb4e0ac555c3b2d0ae814b81795259910/lib/writer.js#L115), we can let influxDB set the time. If the user cares about the time, she can just the time using `.time(X)`. Also we would have to remove the call to `.time()` without an argument.

This would remove the whole handling of the timestamp on the drivers end.

What do you guys think about this?

@vicanso Is there a reason you build it this way?

**Comment by vicanso** [comment]
@cEhlen The timestamps is not necessary in the `toJSON` function. Originally it was used for `queue`, but now `queue` can obtain timestamps. Therefore, the codes you mentioned can be removed.

**Comment by sveip** [comment]
I guess this can be closed now?

**Comment by cEhlen** [comment]
I'm sorry, forgot to close it.
